name: flutter_hook_utils
description: A new Flutter package project.
version: 0.1.0
homepage: https://github.com/KRTirtho/hookified/blob/main/packages/flutter_hook_utils

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
